export const FETCH_PRODUCTS_DTLS_SUCCESS = "FETCH_PRODUCTS_DTLS_SUCCESS";
export const FETCH_PRODUCTS_DTLS_FAILURE = "FETCH_PRODUCTS_DTLS_FAILURE";
export const UPDATE_SEARCH_INP = "UPDATE_SEARCH_INP";
export const ADD_PRODUCT_QTY = "ADD_PRODUCT_QTY";
export const REMOVE_PRODUCT_QTY = "REMOVE_PRODUCT_QTY";
